apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Jenkins-Test-template
  title: Jenkins-Test template
  description: Jenkins-Test template
spec:
  owner: development
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_id
        - environment
      properties:
        component_id:
          title: Component name
          type: string
          description: Provide a component (microservice) name
          pattern: '^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$'
        environment:
          title: Environment
          type: string
          description: The environment where this component will be deployed
          enum:
            - dev
            - prod

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{parameters.component_id}}
          app_env: ${{parameters.environment}}

    - id: publish
      name: Publish
      action: publish:github
      input:
        description: This is ${{ parameters.component_id }}
        repoUrl: github.com?owner=BackstageSSPPoC&repo=${{parameters.component_id}}
        protectDefaultBranch: false
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

    - id: create-k8s-folder
      name: Create K8s Manifest Folder
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=BackstageSSPPoC&repo=k8s-manifests
        branchName: create-${{ parameters.component_id }}
        title: "Add manifests for ${{ parameters.component_id }}"
        description: "This PR creates Kubernetes manifests for ${{ parameters.component_id }}"
        sourcePath: ./manifest-templates
        targetPath: apps/${{ parameters.component_id }}

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}